sudo: false
language: node_js
node_js:
  - "stable"
  - "5"
  - "4"
services:
    - mongodb
    - redis-server
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - python2.7
    - python2.7-dev
# after_success:
#     - npm run coveralls
